source 'https://rubygems.org'

gem 'colorize', '~> 0.7'
gem 'deep_merge', '~> 1.0'
gem 'hiera-eyaml', '~> 2.0'
gem 'librarian-puppet', '~> 2.2'
gem 'metadata-json-lint'
gem 'puppet', '~> 3.8'
gem 'puppet-lint', :git => 'https://github.com/rodjek/puppet-lint.git' # https://github.com/rodjek/puppet-lint/issues/335
gem 'puppet-lint-absolute_classname-check'
gem 'puppet-lint-class_parameter-check'
gem 'puppet-lint-file_ensure-check'
gem 'puppet-lint-file_source_rights-check'
gem 'puppet-lint-leading_zero-check'
gem 'puppet-lint-strict_indent-check'
gem 'puppet-lint-trailing_comma-check'
gem 'puppet-lint-trailing_newline-check'
gem 'puppet-lint-unquoted_string-check'
gem 'puppet-lint-variable_contains_upcase'
gem 'puppetlabs_spec_helper', '~> 1.0'
gem 'rake', '~> 10.4'
gem 'rspec-puppet-utils', '~> 2.2'
